# Generated by Django 2.0 on 2019-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=32)),
                ('password', models.CharField(max_length=22)),
                ('mobileno', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=32)),
            ],
        ),
    ]
